export const ProjectsData = [
  {
    name: "Spotify Clone",
    description: "a spotify clone app made using the spotify API.",
    tools: ["spotify API", "react", "emotionjs", "node.js"],
    liveLink: "https://halkim--spotify.herokuapp.com/",
    codeLink: "https://github.com/halkim44/spotify-clone",
    screenshot: ["project-0301.png", "project-0302.png", "project-0303.png"],
    cover: "project-0301.png",
  },
  {
    name: "Mello ― Trello Clone",
    description:
      "a web-based Kanban-style list-making application. An application that have the basic of the trello clone feature that includes drag and drop feature.",
    tools: ["reactjs", "nodejs", "mongoDB", "bulma.io", "redux"],
    liveLink: "https://pensive-chandrasekhar-8fb2ea.netlify.app/",
    codeLink: "https://github.com/halkim44/trello-clone",
    screenshot: [
      "project-0001.png",
      "project-0002.png",
      "project-0003.png",
      "project-0004.png",
      "project-0005.png",
    ],
    cover: "project-0001.png",
  },
  {
    name: "Manage Landing Page",
    description: "a landing page for a product.",
    tools: ["reactjs", "sass", "responsive"],
    liveLink: "https://halkim44.github.io/manage-landing-page/",
    codeLink: "https://github.com/halkim44/manage-landing-page",
    screenshot: ["project-0101.png", "project-0102.png"],
    cover: "project-0101.png",
  },
  {
    name: "INSURE Landing Page",
    description: "a landing page for a insurance product.",
    tools: ["html", "css", "sass", "responsive"],
    liveLink: "https://halkim44.github.io/insure-landing-page/",
    codeLink: "https://github.com/halkim44/insure-landing-page",
    screenshot: ["project-0201.png", "project-0202.png", "project-0203.png"],
    cover: "project-0201.png",
  },
];
